// Matching BioTime device codes to HR employee records.
//
// Why this exists: public.employees.employee_code is generated by the roster importer from the
// Excel row number ("PPI-0001", "PPJ-HO-0012"), while BioTime emp_codes are device enrolment
// numbers ("101", "1042"). They do not correspond, so an exact-code join links almost nobody and
// all 240-odd staff would need mapping by hand.
//
// So we rank candidates by name similarity and let HR confirm. Two passes:
//   1. exact code match — kept as a fast path in case some codes do line up
//   2. name similarity  — Dice coefficient over character bigrams, blended with token overlap,
//                         nudged by department/area agreement
//
// Nothing here auto-links on a fuzzy score. A wrong auto-link silently files one person's
// attendance under another's name, which is far worse than an unmapped code sitting in an HR
// queue. Only an exact, unambiguous code match auto-links; everything else is a suggestion.

export interface Candidate {
  employeeId: string;
  fullName: string;
  employeeCode: string | null;
  departmentName?: string | null;
  branchName?: string | null;
}

export interface ScoredCandidate {
  employee_id: string;
  full_name: string;
  employee_code: string | null;
  score: number;
  reason: string;
}

/** Honorifics and noise that would otherwise dominate a short-name comparison. */
const TITLES = new Set([
  'mr', 'mrs', 'ms', 'miss', 'dr', 'shri', 'smt', 'sri', 'md', 'mohd',
]);

export function normalizeName(value: string | null | undefined): string {
  if (!value) return '';
  return String(value)
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '') // strip combining accents left by NFKD
    .replace(/[^a-z0-9\s]/g, ' ')      // punctuation -> space ("K.A. Basheer" -> "k a basheer")
    .replace(/\s+/g, ' ')
    .trim();
}

export function nameTokens(value: string | null | undefined): string[] {
  return normalizeName(value)
    .split(' ')
    .filter((t) => t.length > 0 && !TITLES.has(t));
}

function bigrams(value: string): Set<string> {
  const s = value.replace(/\s/g, '');
  const out = new Set<string>();
  for (let i = 0; i < s.length - 1; i++) out.add(s.slice(i, i + 2));
  return out;
}

/** Sørensen–Dice over character bigrams: robust to spelling drift and reordering. */
export function diceCoefficient(a: string, b: string): number {
  if (!a || !b) return 0;
  if (a === b) return 1;

  const A = bigrams(a);
  const B = bigrams(b);
  if (A.size === 0 || B.size === 0) return 0;

  let intersection = 0;
  for (const g of A) if (B.has(g)) intersection += 1;

  return (2 * intersection) / (A.size + B.size);
}

/**
 * Token overlap, which handles the very common case of the same name in a different order or with
 * a missing middle name: "Basheer K A" vs "K A Basheer" scores 1.0 here but poorly on raw bigrams.
 */
export function tokenSetRatio(a: string, b: string): number {
  const A = new Set(nameTokens(a));
  const B = new Set(nameTokens(b));
  if (A.size === 0 || B.size === 0) return 0;

  let shared = 0;
  for (const t of A) if (B.has(t)) shared += 1;

  return shared / Math.min(A.size, B.size);
}

export function nameSimilarity(a: string, b: string): number {
  const na = normalizeName(a);
  const nb = normalizeName(b);
  if (!na || !nb) return 0;
  if (na === nb) return 1;

  // Take the better of the two views, then temper it slightly so a perfect token match on a
  // single common first name ("suresh" vs "suresh") does not outrank a full-name match.
  const dice = diceCoefficient(na, nb);
  const tokens = tokenSetRatio(na, nb);
  const best = Math.max(dice, tokens * 0.95);

  const aTokens = nameTokens(a);
  const bTokens = nameTokens(b);
  const singleTokenPenalty = aTokens.length === 1 || bTokens.length === 1 ? 0.85 : 1;

  return best * singleTokenPenalty;
}

export interface RankOptions {
  /** Ignore anything weaker than this. */
  threshold?: number;
  /** How many suggestions to keep. */
  limit?: number;
}

/**
 * Rank HR employees as candidates for one BioTime record.
 * `deviceCode` is checked for an exact match against employee_code first and, if found, wins outright.
 */
export function rankCandidates(
  device: { empCode: string; fullName: string | null; departmentName?: string | null; areaName?: string | null },
  candidates: Candidate[],
  opts: RankOptions = {}
): ScoredCandidate[] {
  const { threshold = 0.55, limit = 5 } = opts;
  const scored: ScoredCandidate[] = [];

  for (const c of candidates) {
    // Exact code agreement is decisive when it happens.
    if (c.employeeCode && c.employeeCode.toLowerCase() === device.empCode.toLowerCase()) {
      scored.push({
        employee_id: c.employeeId,
        full_name: c.fullName,
        employee_code: c.employeeCode,
        score: 1,
        reason: 'exact code',
      });
      continue;
    }

    if (!device.fullName) continue;

    let score = nameSimilarity(device.fullName, c.fullName);
    if (score < threshold) continue;

    // Small corroborating nudges — never enough to promote a weak name match on their own.
    const reasons: string[] = ['name'];
    if (
      device.departmentName &&
      c.departmentName &&
      normalizeName(device.departmentName) === normalizeName(c.departmentName)
    ) {
      score = Math.min(1, score + 0.04);
      reasons.push('department');
    }
    if (
      device.areaName &&
      c.branchName &&
      normalizeName(device.areaName) === normalizeName(c.branchName)
    ) {
      score = Math.min(1, score + 0.04);
      reasons.push('branch');
    }

    scored.push({
      employee_id: c.employeeId,
      full_name: c.fullName,
      employee_code: c.employeeCode,
      score: Math.round(score * 1000) / 1000,
      reason: reasons.join(' + '),
    });
  }

  return scored.sort((a, b) => b.score - a.score).slice(0, limit);
}

/**
 * Is this ranking safe to auto-apply? Only when it is an exact code hit that no other candidate
 * ties. Fuzzy name scores never auto-link, however confident they look.
 */
export function isAutoLinkable(ranked: ScoredCandidate[]): boolean {
  const exact = ranked.filter((r) => r.reason === 'exact code');
  return exact.length === 1;
}
