// Reports & Analytics — real, branch-wise, scope-based.
//
// Every tab reads through RLS (or the scope-checked attendance service), so the same screen
// serves everyone: a branch manager sees their branch, a zonal manager their zone, the admin all.
// Attendance aggregates come from the report_attendance_summary RPC; the Excel register/payroll
// sheets are generated by the attendance service; the other tabs export CSV client-side.
import React, { useMemo, useState } from 'react';
import {
  BarChart3, CalendarDays, Clock, FileSpreadsheet, Loader2, ReceiptText,
  Users, AlertCircle, Download, SlidersHorizontal, X,
} from 'lucide-react';
import { useOrg } from '../data/org';
import { useEmployees } from '../data/employees';
import { useLeaves } from '../data/leaves';
import { useLeaveTypes, useLeaveBalances } from '../data/leaveTypes';
import { useExpenses } from '../data/expenses';
import { useExits } from '../data/exits';
import { useAttendanceReport } from '../data/reports';
import { useExportRegister, useExportPayroll, todayIso, fmtMinutes, monthRange } from '../data/attendance';
import { useServiceHealth } from '../data/syncStatus';
import { downloadCsv } from '../lib/csv';
import { useUrlTab } from '../lib/useUrlTab';

const inr = (n) => `₹${Number(n || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`;

const th = 'py-2 px-2 text-xs font-bold uppercase tracking-wider text-neutral-450 dark:text-neutral-500';
const td = 'py-1.5 px-2 text-xs font-mono text-neutral-600 dark:text-neutral-300';
const tdName = 'py-1.5 px-2 text-base font-bold text-neutral-800 dark:text-warm-gray-100';

function ReportTable({ headers, rows, footer }) {
  if (rows.length === 0) {
    return <p className="py-8 text-center text-xs text-neutral-500">No data for this period in your scope.</p>;
  }
  return (
    <div className="table-scroll">
      <table className="premium-table w-full text-left">
        <thead>
          <tr className="border-b border-neutral-200/70 dark:border-neutral-850">
            {headers.map((h, i) => (
              <th key={h} className={`${th} ${i > 0 ? 'text-right' : ''}`}>{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((r, ri) => (
            <tr key={ri} className="border-b border-neutral-100 dark:border-neutral-900/60 last:border-0">
              {r.map((cell, ci) => (
                <td key={ci} data-label={headers[ci]} className={ci === 0 ? tdName : `${td} text-right`}>{cell}</td>
              ))}
            </tr>
          ))}
        </tbody>
        {footer && (
          <tfoot>
            <tr className="border-t-2 border-neutral-200 dark:border-neutral-800">
              {footer.map((cell, ci) => (
                <td key={ci} data-label={headers[ci]} className={`${ci === 0 ? tdName : `${td} text-right`} font-bold pt-2`}>{cell}</td>
              ))}
            </tr>
          </tfoot>
        )}
      </table>
    </div>
  );
}

function ExportButton({ label, onClick, pending, disabled, title, icon: Icon = Download }) {
  return (
    <button
      onClick={onClick}
      disabled={pending || disabled}
      title={title} aria-label={title}
      className="flex items-center gap-1.5 rounded-lg border border-neutral-200/80 dark:border-neutral-850 bg-neutral-50/60 dark:bg-charcoal-900/40 px-3 py-1.5 text-base font-bold text-neutral-700 dark:text-warm-gray-300 hover:border-[#0ea971]/40 hover:text-neutral-900 dark:hover:text-white transition-colors cursor-pointer disabled:opacity-50"
    >
      {pending ? <Loader2 size={11} className="animate-spin" /> : <Icon size={11} />}
      {label}
    </button>
  );
}

const TABS = [
  { id: 'attendance', label: 'Attendance', icon: Clock },
  { id: 'leave', label: 'Leave', icon: CalendarDays },
  { id: 'expenses', label: 'Expenses', icon: ReceiptText },
  { id: 'headcount', label: 'Headcount', icon: Users },
];

/** The ids the URL may carry — the tabs that actually render, and nothing else. */
const TAB_IDS = TABS.map((t) => t.id);

export default function ReportsAnalytics() {
  const today = todayIso();
  const [period, setPeriod] = useState(today.slice(0, 7)); // 'YYYY-MM'
  const [branchId, setBranchId] = useState('all');
  const [filtersOpen, setFiltersOpen] = useState(false);
  // In the URL, so a refresh comes back to the report you were reading.
  // The whitelist comes from TABS itself. Hand-written, the two drifted: the list said
  // 'payroll' — a tab that does not exist and renders a blank page at /reports/payroll — and
  // omitted 'expenses', which does exist, so clicking Expenses failed the check and bounced
  // straight back to Attendance. The Expenses report could not be opened at all.
  const [tab, setTab] = useUrlTab('attendance', TAB_IDS);

  const year = Number(period.slice(0, 4));
  const month = Number(period.slice(5, 7));
  const { from, to } = monthRange(year, month);

  const { data: org } = useOrg();
  const { data: employees = [] } = useEmployees();
  const branches = useMemo(
    () => [...(org?.branches ?? [])].sort((a, b) => (a.code || '').localeCompare(b.code || '')),
    [org]
  );
  const selectedBranch = branches.find((b) => b.id === branchId);
  const branchLabel = selectedBranch ? `${selectedBranch.code} — ${selectedBranch.name}` : 'All branches';
  // Match on branch_id, not code: a branch with an empty code made the filter a no-op on three
  // of the four tabs while the attendance tab still filtered — same screen, disagreeing numbers.
  const inBranch = (empBranchId) => branchId === 'all' || empBranchId === branchId;

  // ---- attendance ----
  const { data: attRows = [], isLoading: attLoading, error: attError } = useAttendanceReport(from, to);
  const exportRegister = useExportRegister();
  const exportPayroll = useExportPayroll();
  // Excel files are generated by the attendance service; grey the buttons out when it is
  // unreachable instead of letting the click fail. CSV exports are client-side and always work.
  const serviceHealth = useServiceHealth();
  const serviceDown = serviceHealth.isError;
  const attFiltered = attRows.filter((r) => branchId === 'all' || r.branch_id === branchId);
  const attTotal = attFiltered.reduce(
    (t, r) => {
      for (const k of Object.keys(t)) t[k] += Number(r[k] || 0);
      return t;
    },
    { employees: 0, present_days: 0, half_days: 0, absent_days: 0, leave_days: 0, lop_days: 0, late_marks: 0, missing_punches: 0, ot_minutes: 0 }
  );
  const serviceParams = { year, month, branchIds: branchId === 'all' ? undefined : [branchId] };
  const exportError = exportRegister.error || exportPayroll.error;

  // ---- leave ----
  const { data: leaves = [] } = useLeaves({ enabled: tab === 'leave' });
  const { data: leaveTypes = [] } = useLeaveTypes();
  const { data: allBalances = [] } = useLeaveBalances(null, year, { all: tab === 'leave' });
  const periodLeaves = leaves.filter(
    (l) => l.start_date <= to && l.end_date >= from && inBranch(l.employee?.branch_id)
  );
  const leaveByType = leaveTypes
    .map((t) => {
      const rows = periodLeaves.filter((l) => l.type === t.code || l.type === t.name);
      return {
        type: t.name,
        requests: rows.length,
        approvedDays: rows.filter((l) => l.status === 'Approved').reduce((n, l) => n + Number(l.days || 0), 0),
        pending: rows.filter((l) => l.status === 'Pending').length,
      };
    })
    .filter((r) => r.requests > 0);
  const otherLeaves = periodLeaves.filter(
    (l) => !leaveTypes.some((t) => l.type === t.code || l.type === t.name)
  );

  // Balances carry no branch of their own — scope them through the employee list so the export
  // matches the filter shown on screen.
  const balances = useMemo(() => {
    if (branchId === 'all') return allBalances;
    const ids = new Set(employees.filter((e) => e.branch_id === branchId).map((e) => e.id));
    return allBalances.filter((b) => ids.has(b.employee_id));
  }, [allBalances, branchId, employees]);

  // ---- expenses ----
  const { data: expenses = [] } = useExpenses({ enabled: tab === 'expenses' });
  const periodExpenses = expenses.filter(
    (e) => (e.expense_date || '') >= from && (e.expense_date || '') <= to && inBranch(e.employee?.branch_id)
  );
  const expByCategory = Object.values(
    periodExpenses.reduce((m, e) => {
      const k = e.category || '—';
      m[k] ||= { category: k, claims: 0, approved: 0, pending: 0 };
      m[k].claims += 1;
      if (e.status === 'Approved' || e.status === 'Paid') m[k].approved += Number(e.amount || 0);
      if (e.status === 'Pending') m[k].pending += Number(e.amount || 0);
      return m;
    }, {})
  );

  // ---- headcount ----
  const { data: exits = [] } = useExits({ enabled: tab === 'headcount' });
  const headByBranch = Object.values(
    employees.reduce((m, e) => {
      if (!inBranch(e.branch_id)) return m;
      const code = e.branch?.code || '—';
      m[code] ||= { code, active: 0, joiners: 0, exits: 0 };
      if (e.status === 'Active') m[code].active += 1;
      if (e.join_date && e.join_date >= from && e.join_date <= to) m[code].joiners += 1;
      return m;
    }, {})
  );
  for (const x of exits) {
    const code = x.employee?.branch?.code || '—';
    if (!inBranch(x.employee?.branch_id) || !x.last_day || x.last_day < from || x.last_day > to) continue;
    let row = headByBranch.find((r) => r.code === code);
    if (!row) headByBranch.push((row = { code, active: 0, joiners: 0, exits: 0 }));
    row.exits += 1;
  }
  headByBranch.sort((a, b) => b.active - a.active);

  return (
    <div className="page-shell space-y-5 animate-fade-in">
      <div>
        <h1 className="text-xl font-bold text-neutral-900 dark:text-white leading-tight font-sans flex items-center gap-2">Reports & Analytics</h1>
        <p className="text-xs text-neutral-500 dark:text-neutral-400 mt-0.5">
          Branch-wise operational reports, scoped to what you may see. Pick a month and branch, then export.
        </p>
      </div>

      {/* Filters */}
      <div className="premium-card mobile-filter-card mobile-toolbar flex flex-col sm:flex-row sm:items-center gap-3">
        <input
          type="month"
          value={period}
          max={today.slice(0, 7)}
          onChange={(e) => e.target.value && setPeriod(e.target.value)}
          className="bg-neutral-50 dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-850 rounded-xl px-3 py-1.5 text-xs text-neutral-800 dark:text-neutral-200 focus:outline-none focus:border-[#0ea971]/50"
        />
        {branchId !== 'all' && (
          <div className="mobile-active-filter-row flex flex-wrap items-center gap-1.5 sm:hidden">
            <button
              onClick={() => { setBranchId('all'); setFiltersOpen(false); }}
              className="active-filter-chip inline-flex items-center gap-1.5 rounded-full border border-[#0ea971]/25 bg-[#0ea971]/10 px-2.5 py-1 text-xs font-bold text-[#0c9765] dark:text-[#10b981]"
              title={`Remove ${branchLabel}`}
            >
              <span className="truncate">{branchLabel}</span>
              <X size={12} />
            </button>
          </div>
        )}
        <button
          type="button"
          onClick={() => setFiltersOpen((v) => !v)}
          aria-expanded={filtersOpen}
          className="mobile-filter-toggle sm:hidden"
        >
          <span className="inline-flex items-center gap-1.5">
            <SlidersHorizontal size={14} /> Branch filter
          </span>
          <span>{branchId === 'all' ? 'All' : '1 active'}</span>
        </button>
        <div className={`reports-filter-row mobile-filter-panel ${filtersOpen ? 'is-open' : ''}`}>
          <select
            value={branchId}
            onChange={(e) => {
              setBranchId(e.target.value);
              if (e.target.value !== 'all') setFiltersOpen(false);
            }}
            className="bg-neutral-50 dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-850 rounded-xl px-3 py-1.5 text-xs text-neutral-800 dark:text-neutral-200 focus:outline-none focus:border-[#0ea971]/50 cursor-pointer"
          >
            <option value="all">All branches (in your scope)</option>
            {branches.map((b) => (
              <option key={b.id} value={b.id}>{b.code} — {b.name}</option>
            ))}
          </select>
        </div>
        <div className="mobile-segmented flex gap-1.5 ml-auto">
          {TABS.map((t) => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              aria-current={tab === t.id ? 'page' : undefined}
              className={`flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-base font-bold transition-colors cursor-pointer ${
                tab === t.id
                  ? 'bg-[#0ea971]/15 text-[#0ea971] dark:text-[#10b981] border border-[#0ea971]/25'
                  : 'bg-neutral-100 dark:bg-charcoal-800 text-neutral-500 dark:text-neutral-400 border border-transparent hover:text-neutral-800 dark:hover:text-warm-gray-200'
              }`}
            >
              <t.icon size={11} /> {t.label}
            </button>
          ))}
        </div>
      </div>

      {/* Attendance */}
      {tab === 'attendance' && (
        <section className="premium-card space-y-4">
          <div className="mobile-list-row flex flex-wrap items-center justify-between gap-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-neutral-500 dark:text-neutral-400 flex items-center gap-2">
              <BarChart3 size={13} className="text-[#0ea971]" /> Attendance Summary · {period}
            </h3>
            <div className="mobile-list-actions flex flex-wrap gap-2">
              <ExportButton
                label="Register (Excel)"
                icon={FileSpreadsheet}
                pending={exportRegister.isPending}
                disabled={serviceDown}
                title={serviceDown ? 'Attendance service is unreachable from this device' : undefined}
                onClick={() => exportRegister.mutate(serviceParams)}
              />
              <ExportButton
                label="Payroll Sheet (Excel)"
                icon={FileSpreadsheet}
                pending={exportPayroll.isPending}
                disabled={serviceDown}
                title={serviceDown ? 'Attendance service is unreachable from this device' : undefined}
                onClick={() => exportPayroll.mutate(serviceParams)}
              />
              <ExportButton
                label="Summary (CSV)"
                onClick={() =>
                  downloadCsv(
                    `attendance-summary-${period}.csv`,
                    ['Branch', 'Employees', 'Present', 'Half Day', 'Absent', 'On Leave', 'LOP', 'Late', 'Missing Punch', 'OT Minutes'],
                    attFiltered.map((r) => [
                      `${r.branch_code} ${r.branch_name}`, r.employees, r.present_days, r.half_days,
                      r.absent_days, r.leave_days, r.lop_days, r.late_marks, r.missing_punches, r.ot_minutes,
                    ])
                  )
                }
              />
            </div>
          </div>
          {exportError && (
            <p className="flex items-center gap-1.5 text-xs text-rose-500">
              <AlertCircle size={11} /> Excel export failed: {exportError.message} — is the attendance service running?
            </p>
          )}
          {attError && (
            <p className="flex items-center gap-1.5 text-xs text-rose-500">
              <AlertCircle size={11} /> {attError.message}
            </p>
          )}
          {attLoading ? (
            <p className="py-8 text-center text-xs text-neutral-500">Loading…</p>
          ) : (
            <ReportTable
              headers={['Branch', 'Staff', 'Present', 'Half', 'Absent', 'Leave', 'LOP', 'Late', 'No Punch', 'OT']}
              rows={attFiltered.map((r) => [
                `${r.branch_code} · ${r.branch_name}`, r.employees, r.present_days, r.half_days,
                r.absent_days, r.leave_days, r.lop_days, r.late_marks, r.missing_punches, fmtMinutes(Number(r.ot_minutes)),
              ])}
              footer={attFiltered.length > 1 ? [
                'Total', attTotal.employees, attTotal.present_days, attTotal.half_days, attTotal.absent_days,
                attTotal.leave_days, attTotal.lop_days, attTotal.late_marks, attTotal.missing_punches, fmtMinutes(attTotal.ot_minutes),
              ] : null}
            />
          )}
          <p className="text-2xs text-neutral-400">
            The Excel register has the full per-employee day grid; this table is the per-branch roll-up.
            In the Total row, someone who worked in two branches this month counts once per branch.
          </p>
        </section>
      )}

      {/* Leave */}
      {tab === 'leave' && (
        <section className="premium-card space-y-4">
          <div className="mobile-list-row flex flex-wrap items-center justify-between gap-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-neutral-500 dark:text-neutral-400 flex items-center gap-2">
              <CalendarDays size={13} className="text-[#0ea971]" /> Leave Report · {period}
            </h3>
            <div className="mobile-list-actions flex flex-wrap gap-2">
              <ExportButton
                label="Requests (CSV)"
                onClick={() =>
                  downloadCsv(
                    `leave-report-${period}.csv`,
                    ['Employee', 'Code', 'Branch', 'Type', 'From', 'To', 'Days', 'Status'],
                    periodLeaves.map((l) => [
                      l.employee?.full_name, l.employee?.employee_code, l.employee?.branch?.code,
                      l.type, l.start_date, l.end_date, l.days, l.status,
                    ])
                  )
                }
              />
              <ExportButton
                label="Balances (CSV)"
                onClick={() =>
                  downloadCsv(
                    `leave-balances-${year}.csv`,
                    ['Employee', 'Code', 'Type', 'Entitled', 'Carried Fwd', 'Used', 'Available'],
                    balances.map((b) => [
                      b.employee?.full_name, b.employee?.employee_code, b.leave_type?.name,
                      b.entitled, b.carried_forward, b.used, b.available,
                    ])
                  )
                }
              />
            </div>
          </div>
          <ReportTable
            headers={['Leave Type', 'Requests', 'Approved Days', 'Pending Requests']}
            rows={[
              ...leaveByType.map((r) => [r.type, r.requests, r.approvedDays, r.pending]),
              ...(otherLeaves.length
                ? [[
                    'Other', otherLeaves.length,
                    otherLeaves.filter((l) => l.status === 'Approved').reduce((n, l) => n + Number(l.days || 0), 0),
                    otherLeaves.filter((l) => l.status === 'Pending').length,
                  ]]
                : []),
            ]}
          />
          <p className="text-2xs text-neutral-400">
            {periodLeaves.length} request{periodLeaves.length === 1 ? '' : 's'} overlapping {period} in your scope.
            LOP days appear in the Attendance tab.
          </p>
        </section>
      )}

      {/* Expenses */}
      {tab === 'expenses' && (
        <section className="premium-card space-y-4">
          <div className="mobile-list-row flex flex-wrap items-center justify-between gap-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-neutral-500 dark:text-neutral-400 flex items-center gap-2">
              <ReceiptText size={13} className="text-[#0ea971]" /> Expense Report · {period}
            </h3>
            <ExportButton
              label="Claims (CSV)"
              onClick={() =>
                downloadCsv(
                  `expense-report-${period}.csv`,
                  ['Employee', 'Code', 'Branch', 'Category', 'Date', 'Amount', 'Status', 'Description'],
                  periodExpenses.map((e) => [
                    e.employee?.full_name, e.employee?.employee_code, e.employee?.branch?.code,
                    e.category, e.expense_date, e.amount, e.status, e.description,
                  ])
                )
              }
            />
          </div>
          <ReportTable
            headers={['Category', 'Claims', 'Approved Amount', 'Pending Amount']}
            rows={expByCategory.map((r) => [r.category, r.claims, inr(r.approved), inr(r.pending)])}
            footer={expByCategory.length > 1 ? [
              'Total',
              periodExpenses.length,
              inr(expByCategory.reduce((n, r) => n + r.approved, 0)),
              inr(expByCategory.reduce((n, r) => n + r.pending, 0)),
            ] : null}
          />
        </section>
      )}

      {/* Headcount */}
      {tab === 'headcount' && (
        <section className="premium-card space-y-4">
          <div className="mobile-list-row flex flex-wrap items-center justify-between gap-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-neutral-500 dark:text-neutral-400 flex items-center gap-2">
              <Users size={13} className="text-[#0ea971]" /> Headcount & Movement · {period}
            </h3>
            <ExportButton
              label="Headcount (CSV)"
              onClick={() =>
                downloadCsv(
                  `headcount-${period}.csv`,
                  ['Branch', 'Active Employees', 'Joiners', 'Exits'],
                  headByBranch.map((r) => [r.code, r.active, r.joiners, r.exits])
                )
              }
            />
          </div>
          <ReportTable
            headers={['Branch', 'Active', 'Joiners This Month', 'Exits This Month']}
            rows={headByBranch.map((r) => [r.code, r.active, r.joiners, r.exits])}
            footer={headByBranch.length > 1 ? [
              'Total',
              headByBranch.reduce((n, r) => n + r.active, 0),
              headByBranch.reduce((n, r) => n + r.joiners, 0),
              headByBranch.reduce((n, r) => n + r.exits, 0),
            ] : null}
          />
        </section>
      )}
    </div>
  );
}
